# render.yaml
services:
  - type: web
    name: scrapper
    runtime: node
    buildCommand: |
      npm install
      PUPPETEER_PRODUCT=chrome npm rebuild puppeteer
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: NODE_ENV
        value: production
    plan: starter # REQUIRED - free tier won't work