services:
  - type: web
    name: scrapper
    runtime: node
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y chromium-browser libnss3 libatk1.0-0 libatk-bridge2.0-0 libgbm1 libxshmfence1 libdrm2
      npm install
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium-browser"
      - key: NODE_ENV
        value: production
    plan: starter