services:
  - type: web
    name: scrapper
    runtime: node
    buildCommand: npm install
    startCommand: ./start.sh
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true