services:
  - type: web
    name: scrapper
    runtime: node
    buildCommand: |
      npm install
      sudo apt-get update && sudo apt-get install -y chromium-browser
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: starter # Must be paid plan